Симоновский Д. Л., "Поле для шахмат", гр. 3530901/10001
h31/ProgrammingLabSummer2022Task1 pull request #1
Opened 2022-02-07 22:55 UTC by DafterPlay

2022-02-09 17:37 UTC, h31 requested changes
Классная работа, но некоторые вещи всё-таки нужно исправить. Ещё не проверял тесты и корректность реализации шахматных правил, давайте пока с этими моментами разберемся.

2022-02-09 17:37 UTC, h31 commented on src/main/java/ChessFigure.java
> +public class ChessFigure {
Представим, что я хочу написать UI для ваших шахмат. Написал такой код:
```java
package ru.spbstu.insys.chess;

public class UI {
    ChessFigure figure = new ChessFigure(1, 1, FigureType.PAWN, 'w');
}
```
Не работает. Почему?

2022-02-09 17:37 UTC, h31 commented on src/test/java/ChessFieldTest.java
> +    void checkKing() {
Метод очень длинный и запутанный, если понадобится в нем разобраться, это будет сделать сложно. Как можно это исправить?

2022-02-09 17:37 UTC, h31 commented on src/main/java/ChessField.java
> +        for (ChessFigure chessFigure : piecesWhite)
Допустим, у нас начало партии, на доске 32 фигуры. Чтобы найти нужную, требуется обработать вплоть до 32 объектов. Можно ли как-нибудь более эффективно решить эту задачу?

2022-02-09 17:37 UTC, h31 commented on src/main/java/ChessField.java
> +                piecesWhite.remove(i);
Насколько эффективно удаление из `ArrayList`?

2022-02-09 17:37 UTC, h31 commented on src/main/java/ChessField.java
> +        piecesWhite = new ArrayList<>();
Можно ли перенести инициализацию переменной в другое место, чтобы сократить код?

2022-02-09 17:37 UTC, h31 commented on src/main/java/ChessFigure.java
> +    private final char color;
Есть ли более подходящий тип данных для хранения цвета фигуры?

2022-02-09 17:37 UTC, h31 commented on src/main/java/ChessField.java
> +        if (king1 == null || king2 == null) throw new IllegalArgumentException("King cannot be null");
👍 Проверки - это хорошо

2022-02-09 17:37 UTC, h31 commented on src/main/java/ChessField.java
> +            switch (figure.getFigureType()) {
Обратите внимание на предупреждение

2022-02-09 17:37 UTC, h31 commented on src/main/java/ChessField.java
> +                        boolean canKill = true;
Нужна ли эта переменная?

2022-02-09 17:37 UTC, h31 commented on src/main/java/ChessField.java
> +                        for (ChessFigure defender : defenders)
Чуть выше был такой же код, устраните дублирование

2022-02-09 17:37 UTC, h31 commented on src/main/java/ChessFigure.java
> +        return x == that.x && y == that.y;
Почему две фигуры с одинаковыми координатами, но разными цветами будут равны?

2022-02-09 17:37 UTC, h31 commented on src/main/java/ChessField.java
> +    public boolean addCage(ChessFigure figure) {
https://context.reverso.net/%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4/%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9-%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9/cage
Немного не та клетка

2022-02-09 17:37 UTC, h31 commented on src/main/java/ChessField.java
> +    // Отчистка клетки, кроме короля
А где мы проверяем, что королей не трогаем?

2022-02-09 17:37 UTC, h31 commented on src/main/java/ChessFigure.java
> +    public boolean equals(int x, int y) {
Думаю, лучше переименовать этот метод, чтобы не путать с обычным `equals`

2022-02-09 17:37 UTC, h31 commented on src/main/java/ChessFigure.java
> +    public boolean equals(Object o) {
Если переопределяете `equals`, то нужно переопределять и `hashCode`, см. контракт к `hashCode`

2022-02-09 17:37 UTC, h31 commented on src/main/java/ChessFigure.java
> +    public boolean equals(Object o) {
Кстати, для `ChessField` тоже стоит переопределить `equals`. Мы можем захотеть иметь несколько шахматных досок в программе - например, если пишем ИИ и хотим оценить последствия какого-то хода, не выполняя самого действия

2022-02-09 17:37 UTC, h31 commented on src/main/java/FigureType.java
> +/* package-private */ enum FigureType {
Если `FigureType` является `package-private`, то вы не сможете создать `ChessFigure` из другого пакета. Для проверки попробуйте разместить тесты в другом пакете, нежели сами шахматы.

2022-02-09 17:37 UTC, h31 commented on src/main/java/ChessField.java
> +                        for (ChessFigure defender : defenders)
Несколько мест в программе не покрыто тестами, например, это. Проверьте тестовое покрытие.

2022-02-09 19:02 UTC, DafterPlay commented on src/main/java/ChessField.java
> +            switch (figure.getFigureType()) {
У меня тут не высвечивается предупреждение (скорее всего я его скрыл), но подозреваю вы о том, что я не обрабатываю короля в switch, однако это не имеет никакого смысла т.к. короли не могут стоять на таком расстоянии, чтоб друг-друга съесть

2022-02-09 19:19 UTC, DafterPlay commented on src/main/java/ChessField.java
> +    // Отчистка клетки, кроме короля
В силу особенности программы короли всегда являются нулевым элементом листа, что позволяет игнорировать их, просто начиная пробег массива с 1 (как в данной функции)

2022-02-09 19:24 UTC, DafterPlay commented on src/main/java/ChessField.java
> +                        for (ChessFigure defender : defenders)
Как вы посмотрели, какие части кода покрыты тесами, а какие нет?

2022-02-09 19:30 UTC, h31 commented on src/main/java/ChessField.java
> +            switch (figure.getFigureType()) {
Перейдите на вкладку Files changed, там должно отображаться

> однако это не имеет никакого смысла т.к. короли не могут стоять на таком расстоянии, чтоб друг-друга съесть

Тогда просто добавьте пустую ветвь в `switch`. Можно даже выбросить исключение, если король стоит на недопустимом расстоянии, но это [дискуссионно](https://github.com/h31/ProgrammingLabSummer2022Task1/pull/2#discussion_r803006692) и конкретно в данном случае выглядит несколько избыточным.

2022-02-09 19:33 UTC, h31 commented on src/main/java/ChessField.java
> +                        for (ChessFigure defender : defenders)
https://www.jetbrains.com/help/idea/code-coverage.html
Настройки по умолчанию вполне подойдут

2022-02-09 19:42 UTC, DafterT commented on src/main/java/ChessField.java
> +        for (ChessFigure chessFigure : piecesWhite)
Сказать честно, меня тоже не сильно впечатляет такая реализация, однако более оптимального способа я придумать не смог, разве что хранение "поля" с занятыми координатами, что мне не сильно нравится. Однако если вы требуете именно этого, то я готов реализовать

2022-02-09 20:09 UTC, DafterPlay commented on src/main/java/ChessFigure.java
> +public class ChessFigure {
Причина в том, что я почему-то решил использовать pocket private для своего enumm, что явно является ошибкой, поправил

2022-02-09 20:11 UTC, DafterPlay commented on src/test/java/ChessFieldTest.java
> +    void checkKing() {
Сильно сократил его, вынеся атаки слона и ладьи в отдельные функции. Как уменьшить функцию в дальнейшем не очень представляю, однако мне кажется она достигла нормального уровня читабельности

2022-02-09 20:12 UTC, DafterPlay commented on src/main/java/ChessField.java
> +                piecesWhite.remove(i);
Переделал в `LinkedList` и удаляю по итератору

2022-02-09 20:12 UTC, DafterPlay commented on src/main/java/ChessField.java
> +        piecesWhite = new ArrayList<>();
Да, перенес

2022-02-09 20:16 UTC, DafterPlay commented on src/main/java/ChessFigure.java
> +    private final char color;
Возможно вы подразумеваете bool, однако меня сильно смущает читабельность кода при таком методе хранения цвета. Как вариант я думал использовать еще один enum, однако в таком случае я сильно потеряю по памяти (если я все правильно понимаю)

2022-02-09 20:18 UTC, DafterPlay commented on src/main/java/ChessField.java
> +                        boolean canKill = true;
Если честно не имею представления, как от нее можно избавитьс

2022-02-09 20:19 UTC, DafterPlay commented on src/main/java/ChessFigure.java
> +        return x == that.x && y == that.y;
Зря я вообще полез переопределять метод `equals `. Поправил, добавив свои собственные функции, а `equals` сделал так, как предложила идея

2022-02-09 20:20 UTC, DafterPlay commented on src/main/java/ChessField.java
> +    public boolean addCage(ChessFigure figure) {
Да, поправил.

2022-02-09 20:20 UTC, DafterPlay commented on src/main/java/ChessFigure.java
> +    public boolean equals(int x, int y) {
Да, поправил

2022-02-09 20:20 UTC, DafterPlay commented on src/main/java/ChessFigure.java
> +    public boolean equals(Object o) {
Почему обязательно `equals `идет в связке с `hashCode`?

2022-02-10 11:13 UTC, h31 commented on src/main/java/ChessFigure.java
> +public class ChessFigure {
Всё ещё не работает
<img width="603" alt="image" src="https://user-images.githubusercontent.com/3375923/153395705-dde7f4ac-2f12-4104-ad25-292f9ef3ea97.png">

2022-02-10 11:18 UTC, h31 commented on src/main/java/ChessField.java
> +        for (ChessFigure chessFigure : piecesWhite)
Если вы про двумерный массив, то это вариант, но особого выигрыша он не даст - будет быстрее поиск по координате ячейки, но зато медленнее поиск всех фигур одного цвета.
Вспомните, какие структуры и типы данных вы изучали осенью и как их можно применить в этой задаче.

2022-02-10 11:20 UTC, h31 commented on src/main/java/ChessFigure.java
> +    private final char color;
`boolean` здесь явно не подходит семантически. Насчёт `enum` - как вы оцениваете потери памяти при таком решении? Насколько и почему?

2022-02-10 11:24 UTC, h31 commented on src/main/java/ChessField.java
> +                        boolean canKill = true;
После `canKill = false` вы уже знаете итоговый ответ функции, раз делаете `break`. Нужно ли хранить этот ответ в переменной, если вы можете воспользоваться им сразу же?

2022-02-10 11:35 UTC, h31 commented on src/main/java/ChessFigure.java
> +    public boolean equals(Object o) {
См. [контракт](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#hashCode--), второй пункт. Сейчас у вас два объекта `ChessFigure` с одинаковыми полями будут равны по `equals`, но при этом иметь разный хэш-код, так как по умолчанию он генерируется свой для каждого нового объекта, см. описание по ссылке. [Объяснение](https://stackoverflow.com/questions/2265503/why-do-i-need-to-override-the-equals-and-hashcode-methods-in-java), почему это приведет к проблемам.

2022-02-10 20:43 UTC, DafterPlay commented on src/main/java/ChessFigure.java
> +    private final char color;
Кажется я не так понимал, сколько памяти занимает `enum`, после прочтения информации в интернете, пришел к выводу, что не потеряю в памяти, так что буду переделывать все под `enum`

2022-02-10 20:54 UTC, DafterPlay commented on src/main/java/ChessField.java
> +                        boolean canKill = true;
Ну да, господи, как я сам этого не увидел, поправлю в следующем комите

2022-02-10 21:09 UTC, DafterPlay commented on src/main/java/ChessField.java
> +                        for (ChessFigure defender : defenders)
Спасибо, увидел, добавлю необходимые тесты в следующий комит

2022-02-10 21:10 UTC, DafterPlay commented on src/main/java/ChessField.java
> +        for (ChessFigure chessFigure : piecesWhite)
Я так понимаю вы говорите о `Set`, будет добавлено в следующем комите

2022-02-10 21:12 UTC, DafterPlay commented on src/main/java/ChessField.java
> +            switch (figure.getFigureType()) {
Хорошо, добавлю как пустую ветку в следующем комите. 
Можете объяснить, с чем связана такая необходимость? Почему я должен закрыть свичем все варианты, которые может принимать переменная

2022-02-10 21:20 UTC, DafterPlay commented on src/main/java/ChessFigure.java
> +public class ChessFigure {
Я если честно не имею никаких представлений, с чем это может быть связано и что мне сделать, чтоб это поправить. Можете намекнуть, в какую сторону стоит гуглить?

2022-02-11 19:05 UTC, h31 commented on src/main/java/ChessFigure.java
> +public class ChessFigure {
В сторону того, что у вас все файлы в проекты расположены в пакете по умолчанию (default package)

2022-02-11 19:21 UTC, h31 commented on src/main/java/ChessField.java
> +            switch (figure.getFigureType()) {
1) В 95% случаев пропущенная ветвь в `switch` - это ошибка в коде, т.е. добавили новый вариант в enum и забыли его обработать во всех `switch`-ах программы. Поэтому линтер показывает предупреждение, а не ошибку. Более современные языки в таких случаях могут и ошибку показать.
2) Сейчас вы помните, почему у вас нет ветви для короля, но если придется вернуться к этому коду через условные полгода, то можете не вспомнить. Если вдруг понадобится что-то отладить, можно потратить много времени на выяснение того, почему здесь отсутствует этот код.

2022-02-11 19:22 UTC, h31 commented on src/main/java/ChessField.java
> +        for (ChessFigure chessFigure : piecesWhite)
Да, `Map` или `Set`

2022-02-11 19:37 UTC, h31 commented on src/test/java/ChessFieldTest.java
> +    void checkKing() {
Если честно, ситуация особо не поменялась. Функция всё ещё занимает несколько экранов, это много. Допустим, сломалась проверка в [158](https://github.com/h31/ProgrammingLabSummer2022Task1/pull/1/files#diff-a389a6fa2fe70127d622dab9a33707473ec94970148ce6c89c54f87a7df10c95R158) строке, и мне нужно исправить это. С вами контакта у меня нет, вы уже перешли на другой проект. Как я могу понять, какая расстановка фигур на доске в этот момент? Как я могу понять, в какой из предшествующих вызовов смотреть, чтобы найти проблему?

Идеальный вариант, когда у вас для каждого тестового сценария один метод, или хотя бы один метод на группу похожих сценариев. Подумайте, как это можно организовать.

2022-02-11 21:14 UTC, DafterPlay commented on src/main/java/ChessFigure.java
> +public class ChessFigure {
Хорошо, вас понял, добавлю код в какой-то пакет. Не знал, что оно так будет работать, поправлю в следующем комите

2022-02-11 21:50 UTC, DafterPlay commented on src/test/java/ChessFieldTest.java
> +    void checkKing() {
Я вас не правильно понял, думал вы имеете ввиду не тесты а саму функцию.
Тест для каждой фигуры добавил в отдельные функции

2022-02-19 23:24 UTC, h31 commented on src/main/java/ChessField.java
> +        for (ChessFigure chessFigure : piecesWhite)
Стало лучше, но проблема всё ещё существует. Если клетка пуста, то мы быстро это понимаем и выходим из функции, это хорошо. Если же клетка занята, то продолжаем перебирать, и это уже не очень хорошо. Если есть такое эффективное хранилище, зачем оставлять в программе списки? Это довольно важный момент, подумайте над этим.

Когда решите проблему, подумайте над таким вопросом: зачем нужны два отдельных массива для фигур разного цвета? Почти во всех местах обрабатывается сначала один массив, а за ним другой. Навскидку раздельно обрабатываются черные и белые фигуры только в `checkKing`, и то там все элементы перебираются, поэтому несложно внутри `for` обрабатывать только фигуры нужного цвета. Ну, ещё королей определенного цвета иногда ищем, но ради них оставлять целый массив тоже не очень правильно. Если понадобится, то можно выделить для них отдельную переменную.

2022-02-20 22:38 UTC, DafterPlay commented on src/main/java/ChessField.java
> +        for (ChessFigure chessFigure : piecesWhite)
Если я правильно понимаю, то вы предлагаете убрать все и заменить на один `HashSet`, который бы хранил информацию о всех фигурах.

Из плюсов: 
1. Более красивый код
2. Меньше различных дополнительных действий с разными списками => скорость и память

Из минусов:
1. Реализация. Единственный способ, который я здесь вижу, избавится от всего, оставив прежний функционал, так это заменить `hashCode` и `equals` на сравнение только по `x` и `y` т.к. в противном случае будет сложно удалить какую-то фигуру без полного перебора, однако такое решение не является культурным (если я правильно понял) 
2. Добавление отдельной переменной для королей т.к. в моей программе часто приходится делать несколько проверок, связанных с ними, что невозможно, используя `HashSet`

2022-02-20 22:44 UTC, DafterPlay commented on src/main/java/ChessField.java
> +        for (ChessFigure chessFigure : piecesWhite)
Я понимаю, что переписывание `hashCode` и `equals` подобным образом это скорее всего очень странный способ решения данной проблемы т.к. приведет к проблемам при использовании этого кода другими программистами, которые ожидают от него совсем другого. 
В таком случае я могу сделать `ChessFigure` `package private` и полностью переписать конструктор `ChessField`, но как по мне это уж очень радикальный способ и подозреваю, что вы видите более приемлемый вариант

2022-02-22 13:45 UTC, h31 commented on src/main/java/ChessField.java
> +        for (ChessFigure chessFigure : piecesWhite)
> переписывание hashCode и equals подобным образом это скорее всего очень странный способ решения данной проблемы

Да, всё верно. Смотрели в сторону `Map`?

2022-02-22 13:55 UTC, DafterPlay commented on src/main/java/ChessField.java
> +        for (ChessFigure chessFigure : piecesWhite)
Если честно нет, вы предлагаете хранить в `HashMap` по паре координат саму фигуру? Это должно сработать, спасибо, сейчас перепишу с использованием `Map`, убрав разделение по цветам

2022-02-22 14:34 UTC, h31 commented on src/main/java/ChessField.java
> +        for (ChessFigure chessFigure : piecesWhite)
> вы предлагаете хранить в HashMap по паре координат саму фигуру?

Да

2022-03-11 12:30 UTC, DafterPlay commented
Добавил метод с получением другого цвета в `enum`.  
Убрал лишние переменные в тестах.  
Добавил метод `toString`, чтоб было проще проверять тесты, однако как-то его использовать не стал.  

Рассмотрел вариант с удалением координаты. Все отлично получается до метода `checkKing`, где очень много завязано именно на координатах. В теории все это можно переписать, однако мне не очень нравится, как в таком случае будет выглядеть код (в функции придется передавать либо пару (координата, фигура), либо вообще отдельно фигуру и координату.  

Мне кажется, что код на данном этапе уже достаточно оптимизирован и закончен.

2022-03-18 11:06 UTC, h31 commented
Принимаю работу, оценка 5

2022-03-18 11:13 UTC, h31 approved these changes

2022-03-24 08:16 UTC, closed without merging