Козырев Д.В., "Кватернион", 3530901/10001
h31/ProgrammingLabSummer2022Task1 pull request #2
Opened 2022-02-09 10:28 UTC by PurpleLimon

2022-02-09 19:23 UTC, h31 requested changes

2022-02-09 19:23 UTC, h31 commented on src/main/java/Quaternion.java
> +/* Артём Олегович, здравствуйте!
Здравствуйте, Даниил. Работа правда сделана очень добротно.

Давайте сначала обсудим организационный момент. Если хотите оставить для меня вопрос по коду, используйте для этого Гитхаб. Комментарии в коде для этого лучше не использовать - я отвечу на вопрос, потом вопрос нужно будет убрать, потребуется изменить код - это неаккуратно и не очень удобно.

Хороший вопрос. Универсального ответа тут нет, в целом по возможности лучше делать иммутабельные [value object](https://en.wikipedia.org/wiki/Value_object). В новых версиях Java для этого даже добавили конструкцию `record`. Мутабельные объекты стоит использовать там, где без них никак или когда это позволяет заметно повысить эффективность решения. Почитать по теме: [раз](https://javarush.ru/quests/lectures/questmultithreading.level02.lecture01), [два](https://stackoverflow.com/questions/1284727/mutable-or-immutable-class).

`static` стоит использовать, если вам точно в этом методе не нужны поля класса или так код получается чище, в остальных случаях лучше писать обычные методы. [Материал](https://stackoverflow.com/questions/2671496/when-to-use-static-methods) по теме.

2022-02-09 19:23 UTC, h31 commented on src/main/java/Vector3.java
> +    private static final double equivalenceDelta = 1e-13;
Такая же константа есть в другом файле

2022-02-09 19:23 UTC, h31 commented on src/main/java/Quaternion.java
> +public class Quaternion {
Представим, что я хочу написать игру, и мне понадобился ваш кватернион. Написал такой код:
```java
package ru.spbstu.insys.game;

public class View {
    Quaternion quaternion = new Quaternion();
}
```
Не работает. Почему?

2022-02-09 19:23 UTC, h31 commented on src/main/java/Vector3.java
> +        validateVector(other);
Насколько другой разработчик может ожидать, что `equals` выбросит исключение?

2022-02-09 19:23 UTC, h31 commented on src/main/java/Vector3.java
> +    private static void validateVector(@NotNull Vector3 vector) {
Не забудьте сделать `Reformat code`

2022-02-09 19:23 UTC, h31 commented on src/main/java/Vector3.java
> +import java.security.InvalidParameterException;
Уверены, что ваша ошибка относится к безопасности (`security`)?

2022-02-09 19:23 UTC, h31 commented on src/main/java/Vector3.java
> +        // Не упрощаю по предложению IDE, потому что кажется, что так понятнее
В этом коде явно можно вынести общую часть. Возможно, после этого можно будет воспользоваться рекомендацией IDE без потери читаемости.

2022-02-09 19:23 UTC, h31 commented on src/main/java/Vector3.java
> +    public boolean equals(Object obj) {
Если переопределяете `equals`, то нужно переопределять и `hashCode`, см. контракт к `hashCode`

2022-02-09 19:23 UTC, h31 commented on src/main/java/Quaternion.java
> +    public static double getAngleFromW(double w) {
Больше похоже на `private` метод

2022-02-09 19:23 UTC, h31 commented on src/main/java/Quaternion.java
> +/* Артём Олегович, здравствуйте!
В любом случае, выбрать стоит один вариант и убрать остальные. Сейчас у вас есть dead code в проекте, от него стоит избавиться.

2022-02-09 19:23 UTC, h31 commented on src/main/java/Quaternion.java
> +        } else sb.append(" + ");
Лучше ставить фигурные скобки симметрично, так код будет проще читаться

2022-02-09 19:23 UTC, h31 commented on src/main/java/Quaternion.java
> +            sb.append(" - ");
Вам здесь явно пригодился бы `String.format`

2022-02-09 19:23 UTC, h31 commented on src/main/java/Quaternion.java
> +/* Артём Олегович, здравствуйте!
P.S. `моветон`

2022-02-09 19:23 UTC, h31 commented on src/test/java/QuaternionTest.java
> +        assertEquals(q2.getW(), q1.getW(), 5e-7);
У вас есть константа в коде, которую можно использовать вместо `5e-7`

2022-02-09 19:23 UTC, h31 commented on src/test/java/QuaternionTest.java
> +        assertEquals(new Quaternion(0.3905667329424716, 0.5207556439232954, -0.3905667329424716, -0.6509445549041193),
Есть предложение, как избавиться от этих длиннющих чисел. Вам пришла в голову идея взять калькулятор как эталонную реализацию - это очень хорошая мысль. Давайте пойдем чуть дальше, для Java есть существующие реализации кватернионов, например, в Apache Commons Math. Стоит проверить в рамках автоматических тестов, что ваша реализация даёт такие же результаты, что и эталонная.

2022-02-09 19:23 UTC, h31 commented on src/test/java/QuaternionTest.java
> +        // сравню папарно каждый элемент 2-х кватернионов в отдельных тестах.
`попарно`

2022-02-09 19:23 UTC, h31 commented on src/main/java/Quaternion.java
> +        validateInput(w);
Валидировать данные - это, безусловно, правильно и полезно. Вопрос вызывает другой момент - нужно ли это делать каждый раз, когда мы создаем новый объект. С одной стороны, ошибки лучше обнаруживать как можно раньше (подход [fail fast](https://en.wikipedia.org/wiki/Fail-fast)). С другой, это накладно в плане производительности - выполнять одну и ту же проверку много раз над одинаковыми данными. Кроме того, в таком случае практически любой метод кватерниона может выбросить исключение (мы этого не замечаем, потому что оно unchecked), и не всегда в вызывающем коде мы можем понять, как его обрабатывать. Подумайте, как лучше сделать и какой вариант более предпочтительный в данной задаче.

2022-02-24 12:05 UTC, PurpleLimon commented on src/main/java/Quaternion.java
> +public class Quaternion {
К сожалению, единственное что мне приходит в голову, это то, что Вы не включили в код пакет, в котором реализован кватернион. Я буквально еще раз перепроверил, и IDE никаких ошибок компиляции и выполнения не дает

2022-02-25 11:17 UTC, h31 commented on src/main/java/Quaternion.java
> +public class Quaternion {
<img width="992" alt="image" src="https://user-images.githubusercontent.com/3375923/155706265-54a6ec26-91a4-436e-ae95-587bd7daabc0.png">

2022-03-01 10:02 UTC, PurpleLimon commented on src/main/java/Quaternion.java
> +        validateInput(w);
Я принял решение вообще не делать проверок. Вектор бесконечной длины может быть, а все операции с NaN, вернут NaN, поэтому будет понятно, что что-то идет не так. Для мануальной проверки "Все ли хорошо", просто перепишу метод validateInput на статичный. Думаю, это хороший вариант, т.к. все внутренние операции классов сделаны сейчас безопасно. Так что просто чтобы проследить за состоянием объекта можно будет проверять валидность данных.

2022-03-02 14:46 UTC, PurpleLimon commented
Здравствуйте, Артем Олегович!

Переделал задание по всеми Вашим комментариями, жду Вашего мнения :)
Кажется, что переделано много, но на самом деле классы Vector3 и Quaternion, почти не изменены. Подробно о изменениях в работе написано в комментарии к коммиту.

2022-03-18 11:13 UTC, h31 approved these changes
Сейчас у вас падают тесты, их нужно исправить. Плюс, обратите внимание на предупреждения Qodana. Когда исправите, приму работу, оценка 5.

2022-03-18 11:13 UTC, h31 commented on src/test/java/QuaternionTest.java
> +import java.security.InvalidParameterException;
Лишний импорт

2022-03-18 11:13 UTC, h31 commented on src/test/java/QuaternionTest.java
> +        assertNotEquals(new engine.math.Quaternion(0, 3, 5, 6), new Vector3(0, 3, 6));
Обратите внимание на результат сканирования

2022-03-18 11:13 UTC, h31 commented on src/test/java/QuaternionTest.java
> +
Лишняя пустая строчка

2022-03-24 08:16 UTC, closed without merging