Басов С.А, "Группа студентов", гр. 3530901/10001
h31/ProgrammingLabSummer2022Task1 pull request #6
Opened 2022-03-02 15:09 UTC by BREWYM

2022-03-31 04:39 UTC, h31 requested changes

2022-03-31 04:39 UTC, h31 commented on src/main/java/groupOfStudents/Group.java
> +        if (groupNumber == null || groupNumber.equals(""))
Обратите внимание на предупреждение

2022-03-31 04:39 UTC, h31 commented on src/main/java/groupOfStudents/Group.java
> +        if (description == null || mark == null)
https://docs.oracle.com/javase/8/docs/api/java/util/Objects.html#requireNonNull-T-java.lang.String-

2022-03-31 04:39 UTC, h31 commented on src/main/java/groupOfStudents/Group.java
> +        } else {
Лучше инвертировать условие, сделать, как в `addSubject`

2022-03-31 04:39 UTC, h31 commented on src/main/java/groupOfStudents/StudentDiary.java
> +        if (subjectsMarks.containsKey(subject)) {
Код можно упростить, если инвертировать условие

2022-03-31 04:39 UTC, h31 commented on src/main/java/groupOfStudents/StudentDiary.java
> +            res.append("\n" + k + ": \n");
Предупреждение

2022-03-31 04:39 UTC, h31 commented on src/main/java/groupOfStudents/StudentDiary.java
> +    public StringBuilder getAllMarksAsString() {
`StringBuilder` обычно не возвращают, если мы не планируем что-либо дальше добавлять в него

2022-03-31 04:39 UTC, h31 commented on src/test/java/groupOfStudents/GroupTest.java
> +        IT.toSorted();
Если я убираю весь код из `toSorted`, тесты продолжают проходить. Корректно ли выполняется проверка?

2022-03-31 04:39 UTC, h31 commented on src/test/java/groupOfStudents/GroupTest.java
> +    static Group IT = new Group("3530901/10001");
Почему `static`?

2022-03-31 08:49 UTC, BREWYM commented on src/test/java/groupOfStudents/GroupTest.java
> +    static Group IT = new Group("3530901/10001");
Переделал. Этого просила аннотация BeforeAll, заменил на BeforeEach и убрал static поля у тест-класса.

2022-03-31 08:51 UTC, BREWYM commented on src/test/java/groupOfStudents/GroupTest.java
> +        IT.toSorted();
Да, вы правы. Тут проверка неуместна, так как keySet (в том числе внутри getStudent) создаст отсортированный список. Заменил на вызов переопределенного toString().

2022-03-31 08:52 UTC, BREWYM commented on src/main/java/groupOfStudents/Group.java
> +        if (groupNumber == null || groupNumber.equals(""))
У меня почему-то в этом месте его нет

2022-04-09 11:11 UTC, h31 approved these changes
Принято, оценка 4,5

2022-04-09 11:11 UTC, closed without merging